version: '3.8'

services:
  finance-api:
    build:
      context: ./FinanceRestAPI
      dockerfile: Finance.API/Dockerfile
    ports:
      - "5078:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=db;Database=FinanceDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
    networks:
      - backend

  report-generator:
    build:
      context: ./FinanceRestAPI
      dockerfile: Finance.ReportGenerator/Dockerfile
    volumes:
      - reports:/app/Reports
    depends_on:
      - db
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - finance-api
    environment:
      API_BASE_URL: "http://localhost:5078"
    networks:
      - frontend
      - backend
    volumes:
      - reports:/app/public/reports

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  reports:
